# Imports

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import sys
sys.path.insert(0, '../src/')
%matplotlib inline

import groupdynamics_logs_lib

# Helper functions

In [2]:
import imp
def reload():
    imp.reload(groupdynamics_logs_lib)

In [19]:
reload()

# Parameters

In [20]:
base_directory = '~/Datasets/GroupDynamicsData/'

# Session_304_Report_2020_01_13_17_25_15_gds100
folder_names = [
    'Session_305_Report_2020_01_14_17_44_00_gds101',
    'Session_306_Report_2020_01_18_14_44_54_gds102',
    'Session_307_Report_2020_01_17_16_29_23_gds103']

# Main

In [21]:
folder_name = folder_names[2]

directory = base_directory + folder_name
team_log = groupdynamics_logs_lib.TeamLogsLoader(directory=directory)

In [22]:
answers_in_simple_format = team_log.get_answers_in_simple_format()
influence_orders, influence_matrices = team_log.get_influence_matrices()


# answers_in_simple_format.to_csv('team3_answers.csv', index=False)

In [7]:
answers_in_simple_format

,Question,gds103.1's answer,gds103.1's confidence,gds103.2's answer,gds103.2's confidence
0,asbestos0,$17.00,60,20,85
1,asbestos1,$18,60,20,
2,asbestos2,$18.50,60,18.50,
3,asbestos3,$18.50,70,18.50,
4,disaster0,100 million dollars,60,"10,000",100
5,disaster1,"$50,000",70,"50,000",
6,disaster2,"$75,000",80,"75,000",
7,disaster3,"$75,000",90,"75,000",
8,school0,0.6,75,50,75
9,school1,0.6,80,.6,
10,school2,0.6,90,.6,80
11,school3,0.6,100,.6,
12,sports0,0.5,50,80,85
13,sports1,0.5,70,,
14,sports2,0.6,80,.5,
15,sports3,0.6,80,.5,
16,surgery0,0.3,60,.85,85
17,surgery1,0.3,70,.3,
18,surgery2,0.3,100,.3,
19,surgery3,0.3,100,.3,

In [17]:
for index in range(15):
    print(influence_orders[index])
    print(influence_matrices[index])
    print('\n')

asbestos1
[['60' '']
 ['' '100']]


asbestos2
[['50' '50']
 ['' '90']]


asbestos3
[['60' '40']
 ['' '75']]


disaster1
[['50' '50']
 ['' '50']]


disaster2
[['50' '50']
 ['' '50']]


disaster3
[['70' '30']
 ['' '50']]


school1
[['70' '30']
 ['' '80']]


school2
[['60' '40']
 ['' '80']]


school3
[['60' '40']
 ['' '80']]


sports1
[['50' '50']
 ['' '80']]


sports2
[['70' '30']
 ['30' '80']]


sports3
[['80' '20']
 ['' '50']]


surgery1
[['100' '0']
 ['' '0']]


surgery2
[['100' '0']
 ['' '0']]


surgery3
[['100' '0']
 ['' '0']]

In [23]:
team_log.get_frustrations_in_simple_format()

   Question gds103.1's answer gds103.2's answer
0  asbestos                40
1  disaster                20
2    school                30                25
3    sports                40
4   surgery                20

In [25]:
team_log.frustrations.sort_values('question')

      sender                 question             value            timestamp
3   gds103.1  GD_frustration_asbestos                40  2020-01-17 15:36:08
4   gds103.2  GD_frustration_asbestos  ["Yes","","",""]  2020-01-17 15:36:10
8   gds103.1  GD_frustration_disaster  ["Yes","","",""]  2020-01-17 16:17:31
9   gds103.2  GD_frustration_disaster  ["Yes","","",""]  2020-01-17 16:17:34
10  gds103.1  GD_frustration_disaster                20  2020-01-17 16:17:35
0   gds103.1    GD_frustration_school  ["Yes","","",""]  2020-01-17 15:21:54
1   gds103.1    GD_frustration_school                30  2020-01-17 15:22:00
2   gds103.2    GD_frustration_school                25  2020-01-17 15:22:08
5   gds103.1    GD_frustration_sports  ["","","Yes",""]  2020-01-17 15:49:53
6   gds103.1    GD_frustration_sports                40  2020-01-17 15:49:58
7   gds103.1   GD_frustration_surgery                20  2020-01-17 16:03:47